### ISSUE TITLE
Issue with numeric values for Key

### ISSUE THREAD

**Issue by mfirry** [unicredit/ReactiveAerospike#1]
There's a little inconsistency with the way user key values are stored.

It looks like when using numeric values for keys  they always always get *zero-ed*.

For example: 
`val key = AerospikeKey("test", "my-set", 42)`
If you put such a key you get back:
`AerospikeKey(test,[B@39be40de,Some(my-set),Some(0))`

while if you do the same with a String value for your key (like this
`val key = AerospikeKey("test", "my-set", "aTest")` )
you get out:
`AerospikeKey(test,[B@6a83d1fb,Some(my-set),Some(aTest))`

**Comment by andreaTP** [comment]
fixed in the new version, it was a conversion error from long to int
