### ISSUE TITLE
Publish to Maven

### ISSUE THREAD

**Issue by tdrozdowski** [unicredit/ReactiveAerospike#2]
Please publish to Maven central or another public Maven repository.  This will make it a lot easier/quicker to use the driver within projects.

**Comment by mfirry** [comment]
Hi @tdrozdowski, myself and @andreaTP are still in the process of cleaning up the API a little bit and add proper documentation. We expect to be able to publish it on Sonatype by the end of this week. Also, we're collecting some feedback, so let us know what you think of it you're using it. Thanks!

**Comment by tdrozdowski** [comment]
Will do - just starting to experiment with Aerospike.  Using Play Framework as well - so not sure if you guys have a separate plugin for it similar to the Play-ReactiveMongo plugin or not.

**Comment by tdrozdowski** [comment]
Also - the DAO that you have in the example - seems like it'd be a great candidate for Scala Macros...

**Comment by tdrozdowski** [comment]
Spent time working with it tonight - the DAO documentation needs some updating as it appears its out of sync with where things are now.  Having trouble reading data out of the db via the read() method - the error returned isn't very helpful - as I expect knowing more about the exception being returned would help me determine what's wrong with my model or objRead method.

**Comment by mfirry** [comment]
You're right. As mentioned before, we're doing some cleanup (mainly on the asynchronous support). Docs for DAO are WIP. Thanks so much for your feedback!

**Comment by andreaTP** [comment]
Hi,
thanks a lot for the feedbacks,
the error message handlig is now fixed and more understandable error messages are propagated also to the DAO.
The work of implementing Macro for the Dao is ongoing.
I want to know wich kind of support you need for a Play plugin...
I don't know if have time to work also on this task unfortunately...

Hope @mfirry will help on publishing on sonatype as soon as we have a more stable interface.

**Comment by andreaTP** [comment]
Implemented first draft of macro for the Dao object.
Hope to receive feedback and requests for it!

**Comment by mfirry** [comment]
We've published to Sonatype Snapshot. Check it out! `0.2.0-SNAPSHOT`
