### ISSUE TITLE
Macros - Incompatible with Play Framework JSON Formats

### ISSUE THREAD

**Issue by tdrozdowski** [unicredit/ReactiveAerospike#3]
So, I have been poking at the 0.2-SNAPSHOT and the Macro usage.  Seems that at least for my use case, using Play Framework and serializing the JSON to and from the data case class, the macros get in the way.

The problem is around requiring the id field on the case class - and having that be of type AerospikeKey.  There's no easy way (that I've found) to use the Play Framework Reads/Writes to serialize/deserialize this value - and as such my test application breaks down at this point.

I'm not sure if other JSON frameworks in the Scala world will have this sort of impediment, but thought I would comment to see if you guys had ideas.

**Comment by mfirry** [comment]
Hi Terrence, Andrea just finished a little test. You can have a look and let us know what you think of it: src/test/scala/eu/unicredit/reactive_aerospike/MacroUsage.scala

**Comment by andreaTP** [comment]
Yes, the main code to Reads and writes AerospikeKey is located in 
model/JsonMailDao.scala
Please consider it just an example, production code can be quite different!

**Comment by andreaTP** [comment]
Noticed that accidentally closed issue...
sorry, does the example fit the needs?

**Comment by tdrozdowski** [comment]
Well, sort of.  One thing I noticed was that the Play format for Byte is only available in 2.4 (which isn't released yet) - so I had to back port that into my project to get that to work properly.

I have another issue which may not be related to this - just need a little more time to play with it to be sure.  

Thank you for following up!

One question I had was ... was there any thought to just implementing the full driver in Scala vs wrapping the Java driver?  Similar to the approach that the ReactiveMongo team took?

**Comment by andreaTP** [comment]
Bytes can be translated to json through Integers but you must be careful with the sign... (or with unsigned... ).

Yes I take in account to rewrite the library, but at first we make a wrapper to have a nice experience with scala and the db itself.
Aerospike is a relatively young project and the guys are working a lot on the driver, sometimes adding features to server and driver too, it will be a huge job to follow this changes ...

The ReactiveMongo approach aims to overcome some Casbah and Salat limitations but aerospike-java do not seem to have them at the moment.

Please keep us updated if you run into other kind of troubles!

**Comment by andreaTP** [comment]
Hope, at this point, I can close this.
