### ISSUE TITLE
Remove from list of Aerospike clients

### ISSUE THREAD

**Issue by ericjohnston1989** [unicredit/ReactiveAerospike#6]
Hey guys,

If you've stopped maintaining this project, it'd be best to let Aerospike know so they can remove this project from their list of scala clients.

**Comment by mfirry** [comment]
Hi, please feel free to file issues for missing or unsupported features (and of course bugs).
Also we accept PR. They will make this project move on faster.

**Comment by andreaTP** [comment]
@ericjohnston1989 I've seen that it doesn't appear on the Aerospike site anymore,
from the community page there is a link to https://github.com/Tapad/scaerospike that looks a lot more dismissed than this.

Probably this is a metter of business and not tech goodness.

**Comment by mfirry** [comment]
@ericjohnston1989 can we close this?
